"""Build an FOMC meeting config for a longer sample from the USMPD event times.

Statement and press-conference clocks come from USMPD (Eastern time). Only
scheduled meetings are kept; unscheduled 2019-2020 actions differ in timing and
information content. Before 2019 most meetings had no press conference, so
those entries omit ``press_conference_time_utc`` and use a shorter window.

After running ``scripts/audit_macro_conditions.py --config <this config>``,
pass the resulting report with ``--conditions`` to mark non-available dates.
"""

from __future__ import annotations

import argparse
import json

import pandas as pd
import yaml

from src.events.surprises import USMPD_DIR
from src.utils.config import PROJECT_ROOT


# Federal funds target changes at scheduled meetings (bp), from the Board's
# historical target-range announcements. Unlisted meetings are holds.
POLICY_CHANGES_BPS = {
    "2015-12-16": 25,
    "2016-12-14": 25,
    "2017-03-15": 25,
    "2017-06-14": 25,
    "2017-12-13": 25,
    "2018-03-21": 25,
    "2018-06-13": 25,
    "2018-09-26": 25,
    "2018-12-19": 25,
    "2019-07-31": -25,
    "2019-09-18": -25,
    "2019-10-30": -25,
    "2022-03-16": 25,
    "2022-05-04": 50,
    "2022-06-15": 75,
    "2022-07-27": 75,
    "2022-09-21": 75,
    "2022-11-02": 75,
    "2022-12-14": 50,
    "2023-02-01": 25,
    "2023-03-22": 25,
    "2023-05-03": 25,
    "2023-07-26": 25,
    "2024-09-18": -50,
    "2024-11-07": -25,
    "2024-12-18": -25,
    "2025-09-17": -25,
    "2025-10-29": -25,
    "2025-12-10": -25,
}
PRE_EVENT = pd.Timedelta(minutes=5)
POST_PRESS = pd.Timedelta(minutes=10)
POST_STATEMENT_ONLY = pd.Timedelta(minutes=15)


def _utc(value: pd.Timestamp) -> pd.Timestamp:
    return value.tz_localize("America/New_York").tz_convert("UTC")


def _iso(value: pd.Timestamp) -> str:
    return value.strftime("%Y-%m-%dT%H:%M:%SZ")


def build_meetings(start: str, end: str, conditions: dict[str, str] | None = None) -> list[dict]:
    path = USMPD_DIR / "USMPD.xlsx"
    statements = pd.read_excel(path, "Statements", usecols=["Date", "date_time", "SEP", "Unscheduled"])
    press = pd.read_excel(path, "Press Conferences", usecols=["Date", "date_time"])
    events = statements.merge(press, on="Date", how="left", suffixes=("", "_press"))
    events = events.loc[
        events["Unscheduled"].eq(0) & events["Date"].between(start, end)
    ].sort_values("Date")

    meetings = []
    for row in events.itertuples(index=False):
        date = row.Date.strftime("%Y-%m-%d")
        statement = _utc(row.date_time)
        entry: dict[str, object] = {
            "label": f"fomc_{row.Date:%Y%m%d}",
            "meeting_date": date,
            "statement_time_utc": _iso(statement),
        }
        if pd.notna(row.date_time_press):
            press_time = _utc(row.date_time_press)
            entry["press_conference_time_utc"] = _iso(press_time)
            end_time = press_time + POST_PRESS
        else:
            end_time = statement + POST_STATEMENT_ONLY
        entry.update(
            {
                "request_start_utc": _iso(statement - PRE_EVENT),
                "request_end_utc": _iso(end_time),
                "sep_release": bool(row.SEP),
                "policy_change_bps": POLICY_CHANGES_BPS.get(date, 0),
            }
        )
        condition = (conditions or {}).get(date, "available")
        if condition != "available":
            entry["dataset_condition"] = condition
        meetings.append(entry)
    return meetings


def main() -> None:
    parser = argparse.ArgumentParser(description="Write an FOMC sample config from USMPD event times")
    parser.add_argument("--start", default="2015-01-01")
    parser.add_argument("--end", default="2025-12-31")
    parser.add_argument("--output", default="fomc_sample_2015.yaml", help="File under config/")
    parser.add_argument("--conditions", help="Condition report under reports/ from audit_macro_conditions.py")
    args = parser.parse_args()

    conditions = None
    if args.conditions:
        report = json.loads((PROJECT_ROOT / "reports" / args.conditions).read_text(encoding="utf-8"))
        conditions = {row["date"]: row["condition"] for row in report["conditions"]}
        conditions.update({date: "missing" for date in report["missing_dates"]})

    meetings = build_meetings(args.start, args.end, conditions)
    config = {
        "source_url": "https://sffed.us/usmpd",
        "notes": (
            "Generated by scripts/build_fomc_sample_config.py from USMPD statement and "
            "press-conference clocks (Eastern time converted to UTC). Scheduled meetings only; "
            "meetings without a press conference omit press_conference_time_utc."
        ),
        "meetings": meetings,
    }
    output = PROJECT_ROOT / "config" / args.output
    output.write_text(yaml.safe_dump(config, sort_keys=False), encoding="utf-8")
    with_press = sum("press_conference_time_utc" in m for m in meetings)
    print(f"Wrote {len(meetings)} meetings ({with_press} with press conferences) to {output}")


if __name__ == "__main__":
    main()
