"""Add Employment Situation and PPI windows outside the hand-verified 2024-2025 configs.

Clocks come from ``data/events/bls_release_calendar_2015_2026.csv`` (official BLS
schedule pages). Windows match the existing macro design: five minutes before
through six minutes after the 8:30 a.m. Eastern release. Dates already present
in ``macro_sample_2024.yaml`` / ``macro_sample.yaml`` are left to those files.

Concurrent-release flags cover BLS releases at the same clock and, by rule, the
Thursday unemployment-insurance claims report. Census and BEA releases at the
same clock are NOT screened here for 2015-2023; ``concurrency_screen`` records
that limitation on every row.
"""
from __future__ import annotations

import argparse

import pandas as pd
import yaml

from src.utils.config import PROJECT_ROOT, load_yaml

ADDED = {"employment_situation": "multi_dimensional_numeric", "ppi": "scalar_numeric"}
NAME = {"employment_situation": "employment", "ppi": "ppi"}
HEADLINE = r"^(Employment Situation|Producer Price Index) for "


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--released-through", default=pd.Timestamp.now(tz="UTC").strftime("%Y-%m-%d"))
    parser.add_argument("--output", default="macro_extension_2015_2026.yaml")
    args = parser.parse_args()
    calendar = pd.read_csv(PROJECT_ROOT / "data" / "events" / "bls_release_calendar_2015_2026.csv")
    calendar = calendar.loc[calendar["release_date"].le(args.released_through)]
    same_clock = calendar.loc[calendar["release_time_et"].eq("08:30")]
    covered = set()
    for name in ("macro_sample_2024.yaml", "macro_sample.yaml"):
        for event in load_yaml(PROJECT_ROOT / "config" / name)["events"]:
            covered.add((event["event_date"], event["event_type"]))
    wanted = calendar.loc[
        calendar["release_family"].isin(ADDED) & calendar["release_name"].str.match(HEADLINE)
        & calendar["release_time_et"].eq("08:30")
    ]
    events = []
    for item in wanted.itertuples(index=False):
        if (item.release_date, item.release_family) in covered:
            continue
        clock = pd.Timestamp(item.scheduled_time_utc)
        others = same_clock.loc[
            same_clock["release_date"].eq(item.release_date) & same_clock["release_name"].ne(item.release_name),
            "release_name",
        ].str.replace(r" for .*$", "", regex=True).tolist()
        if clock.tz_convert("America/New_York").dayofweek == 3:
            others.append("Unemployment Insurance Weekly Claims (Thursday rule)")
        events.append({
            "event_id": f"{NAME[item.release_family]}_{item.release_date.replace('-', '')}",
            "event_date": item.release_date,
            "event_time_utc": clock.strftime("%Y-%m-%dT%H:%M:%SZ"),
            "request_start_utc": (clock - pd.Timedelta(minutes=5)).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "request_end_utc": (clock + pd.Timedelta(minutes=6)).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "event_type": item.release_family,
            "reference_period": item.reference_period,
            "representation_class": ADDED[item.release_family],
            "concurrent_release": "|".join(dict.fromkeys(others)) or None,
            "concurrency_screen": "bls_calendar_and_thursday_claims_only",
        })
    config = {
        "source_urls": {"bls_calendar": "https://www.bls.gov/schedule/<year>/home.htm"},
        "notes": (
            "Generated by scripts/build_macro_extension_config.py from the official BLS schedule. "
            "8:30 a.m. Eastern releases; requests span five minutes before through six minutes after. "
            "Census and BEA same-clock releases are not screened for these dates."
        ),
        "events": events,
    }
    output = PROJECT_ROOT / "config" / args.output
    output.write_text(yaml.safe_dump(config, sort_keys=False, width=1000), encoding="utf-8")
    frame = pd.DataFrame(events)
    print(frame.groupby([frame["event_date"].str[:4], "event_type"]).size().unstack(fill_value=0).to_string())
    print(f"Wrote {len(events)} events to {output}")


if __name__ == "__main__":
    main()
